version: "3.9"
services:
  mongo:
    image: mongo
    volumes:
      - ./dataDB:/data/db
  backend:
    image: marcadores_deportivos_b
    ports:
      - "3000:3000"
    environment:
      - URI=mongodb://mongo:27017/
  frontend:
    image: marcadores-deportivos-f
    ports:
      - "8080:80"